version: '3'

vars:
  BUILDER: windsurf-builder
  CONTAINER_NAME: windsurf

tasks:
  setup-act:
    internal: true
    cmds:
      - |
        if ! command -v act &> /dev/null; then
          echo "Installing act..."
          mkdir -p "$HOME/.local/bin"
          curl -s https://raw.githubusercontent.com/nektos/act/master/install.sh | bash -s -- -b "$HOME/.local/bin"
        fi

  setup-builder:
    internal: true
    cmds:
      - |
        if ! docker buildx inspect "{{.BUILDER}}" >/dev/null 2>&1; then
          docker buildx create --name "{{.BUILDER}}" --driver docker-container --bootstrap
        fi
      - docker buildx use "{{.BUILDER}}"

  build:
    desc: Build the Docker image
    deps: [setup-builder]
    cmds:
      - docker buildx bake -f docker-bake.hcl --load develop

  build:test:
    desc: Run the test workflow using act
    deps: [setup-act]
    cmds:
      - task: test-with-env
        vars:
          WORKFLOW: .github/workflows/ci.yml

  test-with-env:
    internal: true
    cmds:
      - |
        if [ -f .env ]; then
          act push -W {{.WORKFLOW}} --env-file .env
        else
          act push -W {{.WORKFLOW}}
        fi

  run:
    desc: Run the windsurf container
    cmds:
      - |
        if docker ps -a --format '{{`{{.Names}}`}}' | grep -q "^{{.CONTAINER_NAME}}$"; then
          echo "Stopping and removing existing container..."
          docker stop "{{.CONTAINER_NAME}}" || true
          docker rm "{{.CONTAINER_NAME}}" || true
        fi
      - >
        docker run --rm -it
        --name "{{.CONTAINER_NAME}}"
        --shm-size=512m
        -p 6901:6901
        -e VNC_PW=password
        ghcr.io/drengskapur/kasmweb-windsurf:develop